### ISSUE TITLE
windows make 관련 오류

### ISSUE THREAD

**Issue by hyungseok-choi** [SNUCSE-CTA/Graph-Pattern-Matching-Challenge#8]
조교님 안녕하세요.
수강생 최형석입니다.

windows OS에서

```
mkdir build
cd build
cmake ..
``` 

![image](https://user-images.githubusercontent.com/63243692/118762395-166e9480-b8b1-11eb-915a-aaed67d12daa.png)

안내사항에 따라 위와 같이 build 폴더를 생성하고,  ```cmake ..``` 명령까지 실행하였습니다.

하지만 이후, make를 위한 Makefile이 생성되지 않는것 같습니다.

![image](https://user-images.githubusercontent.com/63243692/118762646-88df7480-b8b1-11eb-916b-d5e76b65ba87.png)

make 및 g++ 컴파일러는 모두 설치되어 있습니다!

어떻게 해결할 수 있을까요?

**Comment by JihoonJang** [comment]
안녕하세요.

우선 다음 line을 프로젝트 root 폴더의 CMakeLists.txt 파일 맨 앞줄에 추가해보시기 바랍니다.

```bash
SET( CMAKE_CXX_COMPILER "C:/MinGW/bin/g++" )
```
("C:/MinGW/bin/g++" 위치에 g++ compiler의 path를 넣으시면 됩니다.)

또는 WSL 2 (Windows Subsystem for Linux)를 설치 후 해당 환경에서 프로젝트를 수행하시는 것을 추천드립니다.

**Comment by hyungseok-choi** [comment]
답변 감사드립니다!

![image](https://user-images.githubusercontent.com/63243692/119066644-2d30fa80-ba1b-11eb-880a-8d5e9dca5f84.png)
g++ path 확인후

![image](https://user-images.githubusercontent.com/63243692/119066394-a54af080-ba1a-11eb-911e-713126382662.png)
말씀해준대로 위와 같이 한줄을 추가하고 시도하였으나 결과는 동일하게 나타났습니다! 

WSL2를 설치중이기는 하나, windows환경에서 이를 해결할 수 있는 방법은 없을까요?

**Comment by JihoonJang** [comment]
아마 컴파일러 path의 문제인 것 같습니다.

다음 링크를 참고해보시면 도움이 될 것 같습니다.

https://stackoverflow.com/questions/51509173/how-can-i-make-cmake-use-mingw-w64-gcc-g
